Cálculo del deflactor con el índice de inflación y una columna base 100 para agosto de 1994

In [25]:
import pandas as pd
import numpy as np

In [4]:
pi = pd.Series([1.86,1.53,2.62,2.81,1.71,1.70,1.02,1.55,2.43,2.67,2.26,2.36,0.99,0.99,1.41,1.47,1.56,1.34,1.03,0.35,1.26,1.22,1.19,1.11,0.44,0.15,0.30,0.32,0.47,1.18,0.50,0.51,0.88,0.41,0.54,0.22,-0.02,0.06,0.23,0.17,0.43,0.71,0.46,0.34,0.24,0.50,0.02,-0.12,-0.51,-0.22,0.02,-0.12,0.33,0.70,1.05,1.10,0.56,0.3,0.19,1.09,0.56,0.31,1.19,0.95,0.6,0.62,0.13,0.22,0.42,0.01,0.23,1.61,1.31,0.23,0.14,0.32,0.59,0.57,0.46,0.38,0.58,0.41,0.52,1.33,0.7,0.28,0.83,0.71,0.65,0.52,0.36,0.60,0.80,0.21,0.42,1.19,0.65,0.72,1.31,3.02,2.1,2.25,1.57,1.23,0.97,0.61,-0.15,0.2,0.34,0.78,0.29,0.34,0.52,0.76,0.61,0.47,0.37,0.51,0.71,0.91,0.69,0.33,0.44,0.69,0.86,0.58,0.59,0.61,0.87,0.49,-0.02,0.25,0.17,0.35,0.75,0.55,0.36,0.59,0.41,0.43,0.21,0.1,-0.21,0.19,0.05,0.21,0.33,0.31,0.48,0.44,0.44,0.37,0.25,0.28,0.28,0.24,0.47,0.18,0.3,0.38,0.74,0.54,0.49,0.48,0.55,0.79,0.74,0.53,0.28,0.26,0.45,0.36,0.28,0.48,0.55,0.2,0.48,0.47,0.36,0.24,0.15,0.24,0.28,0.41,0.37,0.75,0.78,0.52,0.57,0.43,0,0.01,0.04,0.45,0.75,0.83,0.63,0.83,0.8,0.79,0.77,0.47,0.15,0.16,0.37,0.53,0.43,0.52,0.5,0.56,0.45,0.21,0.64,0.36,0.08,0.43,0.41,0.57,0.59,0.6,0.79,0.86,0.6,0.47,0.55,0.37,0.26,0.03,0.24,0.35,0.57,0.54,0.92,0.55,0.69,0.92,0.67,0.46,0.4,0.01,0.25,0.57,0.42,0.51,0.78,1.24,1.22,1.32,0.71,0.74,0.79,0.62,0.22,0.54,0.82,1.01,0.96])
pi

0      1.86
1      1.53
2      2.62
3      2.81
4      1.71
       ...
252    0.22
253    0.54
254    0.82
255    1.01
256    0.96
Length: 257, dtype: float64

In [11]:
inf = pd.DataFrame(pi, columns=['inf'])
inf

      inf
0    1.86
1    1.53
2    2.62
3    2.81
4    1.71
..    ...
252  0.22
253  0.54
254  0.82
255  1.01
256  0.96

[257 rows x 1 columns]

In [50]:
inf['ano'] = 0
inf

      inf  ano
0    1.86    0
1    1.53    0
2    2.62    0
3    2.81    0
4    1.71    0
..    ...  ...
252  0.22    0
253  0.54    0
254  0.82    0
255  1.01    0
256  0.96    0

[257 rows x 2 columns]

In [51]:
inf['ano'][0:5]=1994
inf['ano'][5:17]=1995
inf['ano'][17:29]=1996
inf['ano'][0:5]=1997
inf['ano'][0:5]=1998
inf['ano'][0:5]=1999
inf['ano'][0:5]=2000
inf['ano'][0:5]=2011
inf['ano'][0:5]=2002
inf['ano'][0:5]=2003
inf['ano'][0:5]=2004
inf['ano'][0:5]=2005
inf['ano'][0:5]=2006
inf['ano'][0:5]=2007
inf['ano'][0:5]=2008
inf['ano'][0:5]=2009
inf['ano'][0:5]=2010
inf['ano'][0:5]=2011
inf['ano'][0:5]=2012
inf['ano'][0:5]=2013
inf['ano'][0:5]=2014
inf['ano'][0:5]=2015

C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=1994
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][5:16]=1995
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=1996
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=1997
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=1998
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=1999
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2000
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2011
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2002
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2003
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2004
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2005
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2006
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2007
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2008
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2009
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2010
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2011
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2012
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2013
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2014
C:\Users\PATRICIO\AppData\Local\Temp\ipykernel_16280\2372212283.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inf['ano'][0:5]=2015

In [53]:
for x in an:

     inf   ano
0   1.86  2015
1   1.53  2015
2   2.62  2015
3   2.81  2015
4   1.71  2015
5   1.70  1995
6   1.02  1995
7   1.55  1995
8   2.43  1995
9   2.67  1995
10  2.26  1995
11  2.36  1995
12  0.99  1995
13  0.99  1995
14  1.41  1995
15  1.47  1995
16  1.56     0
17  1.34     0
18  1.03     0
19  0.35     0

In [55]:
ano = np.arange(1994,2016)
ano

array([1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015])